#=============================================================================
# Azure Pipeline settings
#=============================================================================

trigger:
- pramodk/azure-support-ticket

jobs:

- job: 'WindowsInstaller'
  pool:
    vmImage: windows-2019
  steps:
    - pwsh: |
        #Invoke-WebRequest -MaximumRetryCount 2 -OutFile nrn.exe https://raw.githubusercontent.com/pramodk/nrn/nrnexe/nrn8.0setup-AMD64.exe
        Invoke-WebRequest -MaximumRetryCount 2 -OutFile nrn.exe https://github.com/pramodk/nrn/releases/download/nightly/nrn8.0setup-AMD64.exe
        dir .
    - script: |
        echo "1.------------------"
        nrn.exe /S
        echo "2.------------------"
        dir C:\nrn
      displayName: "Install EXE"
