#=============================================================================
# Azure Pipeline NEURON settings
#=============================================================================
variables:
   INSTALL_DIR: $(Agent.HomeDirectory)/install
jobs:
- job: 'ubuntu1804'
  pool:
    vmImage: 'ubuntu-18.04'
  displayName: 'Ubuntu (18.04), GCC 7.5'
  steps:
  - script: |
      sudo apt update
      sudo apt install -y flex bison doxygen libopenmpi-dev \
                          libmpich-dev libx11-dev libxcomposite-dev mpich openmpi-bin libncurses-dev
    displayName: 'Install System Depdendencies'
  - template: azure-build.yml

- job: 'osx1015'
  pool:
    vmImage: 'macOS-10.15'
  displayName: 'MacOS (10.15), AppleClang 11.03'
  variables:
    EXTRA_PATH: '/usr/local/opt/flex/bin:/usr/local/opt/bison/bin'
  steps:
  - script: |
      brew cask install xquartz
      brew install flex bison doxygen mpich
      brew unlink mpich && brew install openmpi
      echo $'[install]\nprefix='>$(Agent.HomeDirectory)/.pydistutils.cfg
    displayName: 'Install System Depdendencies'
  - template: azure-build.yml
