#=============================================================================
# Azure Pipeline settings
#=============================================================================

# Used for neuron-nightly wheel
variables:
  NEURON_NIGHTLY_TAG: '-nightly'

jobs:

- job: 'ManyLinuxWheels'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Python35:
        python.azure.version: '3.5'
      Python36:
        python.azure.version: '3.6'
      Python37:
        python.azure.version: '3.7'
      Python38:
        python.azure.version: '3.8'
  steps:
  - script: |
      docker run --rm \
        -w /root/nrn \
        -v $PWD:/root/nrn \
        -e NEURON_NIGHTLY_TAG \
        'neuronsimulator/neuron_wheel' \
        packaging/python/build_wheels.bash linux $(python.azure.version)
    displayName: 'Building ManyLinux Wheel'

  - script: |
      sudo apt update
      sudo apt install -y mpich openmpi-bin libopenmpi-dev libmpich-dev
    displayName: 'Install Test System Depdendencies'

  - template: azure-wheel-test.yml


