#=============================================================================
# Azure Pipeline settings
#=============================================================================

# Used for neuron-nightly wheel
variables:
  NEURON_NIGHTLY_TAG: '-nightly'

# Nightly build master for pypi upload
schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - master
  always: true

# Auto cancel old PR builds
pr:
  autoCancel: true

# Trigger build for certain branches only
trigger:
- master
- releases/*
- pramodk/azure-windows-ci

jobs:

- job: 'ManyLinuxWheels'
  condition: eq(1,2)
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - script: |
      docker run --rm \
        -w /root/nrn \
        -v $PWD:/root/nrn \
        -e NEURON_NIGHTLY_TAG \
        'neuronsimulator/neuron_wheel' \
        packaging/python/build_wheels.bash linux $(python.version)
    displayName: 'Building ManyLinux Wheel'

  - script: |
      sudo apt update
      sudo apt install -y mpich openmpi-bin libopenmpi-dev libmpich-dev
    displayName: 'Install Test System Depdendencies'

  - template: ci/azure-wheel-test-upload.yml


# Jobs to build OSX wheels natively
- job: 'MacOSWheels'
  condition: eq(1,2)
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
        python.org.version: '3.5.4'
      Python36:
        python.version: '3.6'
        python.org.version: '3.6.8'
      Python37:
        python.version: '3.7'
        python.org.version: '3.7.7'
      Python38:
        python.version: '3.8'
        python.org.version: '3.8.2'
  steps:

  - script: |
      if [ "$(python.org.version)" == "3.5.4" ]; then
        installer=python-$(python.org.version)-macosx10.6.pkg
      else
        installer=python-$(python.org.version)-macosx10.9.pkg
      fi
      url=https://www.python.org/ftp/python/$(python.org.version)/$installer
      curl $url -o $installer
      sudo installer -pkg $installer -target /
    displayName: 'Install Python from python.org'

  - script: |
      brew cask install xquartz
      brew install flex bison mpich
      brew unlink mpich && brew install openmpi
    displayName: 'Install OSX System Depdendencies'

  - script: |
      export MACOSX_DEPLOYMENT_TARGET=10.9
      export PATH=/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH
      export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
      packaging/python/build_wheels.bash osx $(python.version)
    displayName: 'Build MacOS Wheel'

  - template: ci/azure-wheel-test-upload.yml

- job: 'WindowsInstaller'
  pool:
    vmImage: windows-2019
  variables:
    MSYS2_ROOT: C:\msys64
  continueOnError: false
  steps:
    - task: BatchScript@1
      inputs:
        filename: ci/win_download_deps.cmd
      displayName: "Download Dependencies"
      condition: and(succeeded(), eq(1,1))
    - task: BatchScript@1
      inputs:
        filename: ci/win_install_deps.cmd
      displayName: "Install Dependencies"
      condition: and(succeeded(), eq(1,1))
    - script: |
        %MSYS2_ROOT%\usr\bin\bash -lc "$BUILD_SOURCESDIRECTORY/ci/win_build_cmake.sh"
      displayName: "Build and Create Installer"
      condition: and(succeeded(), eq(1,1))
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
      displayName: "Use System Python"
    - task: BatchScript@1
      inputs:
        filename: ci/win_test_installer.cmd
      displayName: "Test Installer"
      condition: and(succeeded(), eq(1,1))
    - task: GithubRelease@0
      inputs:
        gitHubConnection: pramodk-nrn-fork
        repositoryName: neuronsimulator/installers
        action: create
        tagSource: manual
        tag: nightly
        title: 'Nightly NEURON Release'
        isPreRelease: true
        assetUploadMode: replace
        addChangeLog: true
        assets: |
          $(Build.SourcesDirectory)\build\src\mswin\nrn8.0setup-AMD64.exe
      displayName: 'Upload Installer'
      condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'Schedule', 'IndividualCI', 'PullRequest'))
